on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 2 * * *"
jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkin
        run: |
          pip install BeautifulSoup4
          import requests
          import sys
          import traceback
          from bs4 import BeautifulSoup
          form_data = {
            "email": "${{secrets.SOCKBOOM_USER}}",
            "passwd": "${{secrets.SOCKBOOM_PASSWD}}"
          }
          s = requests.Session()
          def run(form_data):
              response = s.post("${{secrets.SOCKBOOM_URL}}/auth/login", data=form_data)
              print(response.text)
              print(response.status_code)
              if response.status_code == 200:
                resp = s.post("${{secrets.SOCKBOOM_URL}}/user/checkin")
                print(resp.json())
                if resp.status_code == 200:
                  if "${{secrets.WEB_HOOK}}":
                    msg_data = {
                      "msgtype": "markdown",
                      "markdown": {
                        "content": response.json()['user'] + "，签到，<font color=\"warning\">"+ resp.json()['msg'] + "</font>"
                      }
                    }
                    s.post("${{secrets.WEB_HOOK}}", json=msg_data)
                    getUserInfo()
          def getUserInfo():
            userinfo = s.get("${{secrets.SOCKBOOM_URL}}/user")
            if userinfo.status_code == 200:
              try:
                bs = BeautifulSoup(userinfo.text, 'html.parser')
                ul = bs.find_all("ul", "unstyled")[0]
                li = ul.find_all("li")
                info = ""
                for item in li:
                  value = item.find_all("span", "pull-right")[0]
                  label = value.previous_sibling
                  info += label + value.string + "\n"
                print("当前时间：" + time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(time.time())) + "\n" + info)
                msg_data = {
                  "msgtype": "markdown",
                  "markdown": {
                    "content": "当前时间：" + time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(time.time())) + "\n" + info
                  }
                }
                s.post("${{secrets.WEB_HOOK}}", json=msg_data)
              except Exception as e:
                print(e)
          def main():
              run(form_data)
              print("main")
          if __name__ == '__main__':
              try:
                  sys.exit(main())
              except Exception as e:
                  traceback.print_exc()
        shell: python
#
