on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 2 * * *"
jobs:
  checkin: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkin
        run: |
          import requests
          import sys
          import traceback
          form_data = {
            "email": "${{secrets.SOCKBOOM_USER}}",
            "passwd": "${{secrets.SOCKBOOM_PASSWD}}"
          }
          def run(form_data):
              s = requests.Session()
              response = s.post("${{secrets.SOCKBOOM_URL}}/auth/login", data=form_data)
              print(response.text)
              print(response.status_code)
              if response.status_code == 200:
                resp = s.post("${{secrets.SOCKBOOM_URL}}/user/checkin")
                print(resp.json())
                if resp.status_code == 200:
                  if "${{secrets.WEB_HOOK2}}":
                    print('存在')
                    # if resp.json()['ret'] == 0:
                    #   msg_data = {
                    #     "msgtype": "markdown",
                    #     "markdown": {
                    #       "content": "${{secrets.SOCKBOOM_USER}}" + "，签到成功，获得<font color=\"warning\">"+ resp.json()['msg'] + "</font>"
                    #     }
                    #   }
                    #   s.post("${{secrets.WEB_HOOK}}", json=msg_data)
                    # else:
                    #   msg_data = {
                    #     "msgtype": "markdown",
                    #     "markdown": {
                    #       "content": "${{secrets.SOCKBOOM_USER}}" + "，签到失败，<font color=\"warning\">" + resp.json()['msg'] + "</font>"
                    #     }
                    #   }
                    #   s.post("${{secrets.WEB_HOOK}}", json=msg_data)
                  else:
                    print('不存在')
          def main():
              run(form_data)
              print("run1")
          if __name__ == '__main__':
              try:
                  sys.exit(main())
              except Exception as e:
                  traceback.print_exc()
        shell: python
#