on:
  schedule:
    - cron: "0 2 * * *"
jobs:
  checkin: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkin
        run: |
          import requests
          import sys
          import traceback
          form_data = {
            "email": "${{secrets.SOCKBOOM_USER}}",
            "passwd": "${{secrets.SOCKBOOM_PASSWD}}"
          }
          def run(form_data):
              s = requests.Session()
              response = s.post("${{secrets.SOCKBOOM_URL}}/auth/login", data=form_data)
              print(response.text)
              print(response.status_code)
              if response.status_code == 200:
                resp = s.post("${{secrets.SOCKBOOM_URL}}/user/checkin")
                print(resp.json())
                if resp.status_code == 200:
                  if "${{secrets.WEB_HOOK}}":
                    msg_data = {
                      "msgtype": "markdown",
                      "markdown": {
                        "content": response.json()['user'] + "，签到，<font color=\"warning\">"+ resp.json()['msg'] + "</font>"
                      }
                    }
                    s.post("${{secrets.WEB_HOOK}}", json=msg_data)
          def main():
              run(form_data)
              print("main")
          if __name__ == '__main__':
              try:
                  sys.exit(main())
              except Exception as e:
                  traceback.print_exc()
        shell: python
#